[workspace]
resolver = "2"
members = [
    "lib-checker",
    "memory-pool",
    "montgomery-modular",
    "number",
    "persistent-array",
    "union-find",
    "z-algorithm",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
criterion = "0.5.1"
rand = "0.8.5"
